# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: 'Build'
  displayName: 'Build the app'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
      workingDirectory: './test-pipelines' 
      displayName: 'install Angular and proyect dependencies'


    - script: |
        ng build --prod --output-path $(Build.ArtifactStagingDirectory)
      workingDirectory: './test-pipelines' 
      displayName: 'build Angular proyect'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publishing Artifact in drop'

- stage: 'Deploy'
  displayName: 'Deploy the app'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
     vmImage: 'ubuntu-latest'
    environment: dev
    strategy:
     runOnce:
      deploy:
       steps:
       - task: DownloadBuildArtifacts@0
         inputs:
           buildType: 'current'
           downloadType: 'single'
           artifactName: 'drop'
           downloadPath: '$(System.ArtifactsDirectory)'
       - task: AzureWebApp@1
         inputs:
          azureSubscription: 'test'
          appType: webAppLinux
          appName: 'test-pipelines'
          package: '$(System.ArtifactsDirectory)'
